#!/usr/bin/env bash
# Configures custom IP resolutions for localhost and facebook.com.

tmp_hosts="$(mktemp)"
trap 'rm -f "$tmp_hosts"' EXIT

sed -e 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' \
    -e '/facebook\.com/d' /etc/hosts > "$tmp_hosts"
echo "8.8.8.8 facebook.com" >> "$tmp_hosts"
cat "$tmp_hosts" > /etc/hosts
